### ISSUE TITLE
How to replace files?

### ISSUE THREAD

**Issue by Bluscream** [SnowVolf/PCompiler#3] opened 2018-11-10 19:39 UTC
I tried:
```
[MIN_ENGINE_VER]
1

[AUTHOR]
Bluscream

[PACKAGE]
com.teamspeak.ts3client


# Remove original entry
[ADD_FILES]
SOURCE:
    teaspeak.zip
TARGET:
    /
EXTRACT:
	true
[/ADD_FILES]

[MATCH_REPLACE]
TARGET:
	AndroidManifest.xml
MATCH:
REGEX:
	false
REPLACE:
[/MATCH_REPLACE]
```

But it errors out with "File already exists"

**Comment by 02629524272** [comment] 2020-02-20 05:03
Duplicate of #

**Comment by 02629524272** [comment] 2020-02-20 05:16
> I tried:
> 
> ```
> [MIN_ENGINE_VER]
> 1
> 
> [AUTHOR]
> Bluscream
> 
> [PACKAGE]
> com.teamspeak.ts3client
> 
> 
> # Remove original entry
> [ADD_FILES]
> SOURCE:
>     teaspeak.zip
> TARGET:
>     /
> EXTRACT:
> 	true
> [/ADD_FILES]
> 
> [MATCH_REPLACE]
> TARGET:
> 	AndroidManifest.xml
> MATCH:
> REGEX:
> 	false
> REPLACE:
> [/MATCH_REPLACE]
> ```
> 
> But it errors out with "File already exists"

**Closed** 2022-09-11 15:33 UTC
