### ISSUE TITLE
https://github.com/SnowVolf/PCompiler/issues/3#issue-379454348

### ISSUE THREAD

**Issue by Ssieef** [SnowVolf/PCompiler#6] opened 2020-01-25 07:27 UTC
https://github.com/SnowVolf/PCompiler/issues/3#issue-379454348

**Comment by 02629524272** [comment] 2020-02-20 04:58
https://github.com/SnowVolf/PCompiler/issues/6#issue-555054324

**Comment by 02629524272** [comment] 2020-02-20 05:01
https://github.com/SnowVolf/PCompiler/issues/6#issuecomment-588609997

**Comment by 02629524272** [comment] 2020-02-20 05:02
> [#3 (comment)](https://github.com/SnowVolf/PCompiler/issues/3#issue-379454348)

**Comment by 02629524272** [comment] 2020-02-20 05:12
Duplicate of #

**Comment by 02629524272** [comment] 2020-02-20 05:12
Duplicate of #

**Comment by 02629524272** [comment] 2020-02-20 05:13
@SnowVolf

**Comment by uy9138416** [comment] 2020-06-01 10:24
Issue for the Bulid

**Comment by uy9138416** [comment] 2020-06-01 10:26
Issue is this app not bulid

**Comment by SnowVolf** [comment] 2022-09-10 15:27
Fixed [d82fe18](https://github.com/SnowVolf/PCompiler/commit/d82fe18814db2641fcdb1077394ad94ad39a75e2)

**Closed** 2022-09-10 15:27 UTC
